version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
     - "127.0.0.1:8080:8080"

    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/codeChallenge003Database
      - SPRING_DATASOURCE_USERNAME=mohammad
      - SPRING_DATASOURCE_PASSWORD=codeChallenge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=codeChallenge003Database
      - POSTGRES_USER=mohammad
      - POSTGRES_PASSWORD=codeChallenge

  rabbitmq:
      image: "rabbitmq:3-management"
      container_name: "rmq3"
      restart: "no"
      environment:
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
      labels:
        NAME: "rabbitmq1"
      ports:
        - "5672:5672"
        - "15672:15672"


